create table EUR_USD_TABLE(ask_price double, bid_price double, insert_time timestamp default current_timestamp primary key);
create table EUR_USD_1m_TABLE(start_price double, end_price double, max_price double, min_price double, uppersigma1 double default NULL, lowersigma1 double default NULL, uppersigma2 double default NULL, lowersigma2 double default NULL, uppersigma3 double default NULL, lowersigma3 double default NULL, sma20 double default NULL, sma40 double default NULL, sma80 double default NULL, sma100 double default NULL, sma200 double default NULL, insert_time timestamp not null primary key);
create table EUR_USD_5m_TABLE(start_price double, end_price double, max_price double, min_price double, uppersigma1 double default NULL, lowersigma1 double default NULL, uppersigma2 double default NULL, lowersigma2 double default NULL, uppersigma3 double default NULL, lowersigma3 double default NULL, sma20 double default NULL, sma40 double default NULL, sma80 double default NULL, sma100 double default NULL, sma200 double default NULL, insert_time timestamp not null primary key);
create table EUR_USD_1h_TABLE(start_price double, end_price double, max_price double, min_price double, uppersigma1 double default NULL, lowersigma1 double default NULL, uppersigma2 double default NULL, lowersigma2 double default NULL, uppersigma3 double default NULL, lowersigma3 double default NULL, sma20 double default NULL, sma40 double default NULL, sma80 double default NULL, sma100 double default NULL, sma200 double default NULL, insert_time timestamp not null primary key);
create table EUR_USD_day_TABLE(start_price double, end_price double, max_price double, min_price double, uppersigma1 double default NULL, lowersigma1 double default NULL, uppersigma2 double default NULL, lowersigma2 double default NULL, uppersigma3 double default NULL, lowersigma3 double default NULL, sma20 double default NULL, sma40 double default NULL, sma80 double default NULL, sma100 double default NULL, sma200 double default NULL, insert_time timestamp not null primary key);


create table GBP_USD_TABLE(ask_price double, bid_price double, insert_time timestamp default current_timestamp primary key);
create table GBP_USD_1m_TABLE(start_price double, end_price double, max_price double, min_price double, uppersigma1 double default NULL, lowersigma1 double default NULL, uppersigma2 double default NULL, lowersigma2 double default NULL, uppersigma3 double default NULL, lowersigma3 double default NULL, sma20 double default NULL, sma40 double default NULL, sma80 double default NULL, sma100 double default NULL, sma200 double default NULL, insert_time timestamp not null primary key);
create table GBP_USD_5m_TABLE(start_price double, end_price double, max_price double, min_price double, uppersigma1 double default NULL, lowersigma1 double default NULL, uppersigma2 double default NULL, lowersigma2 double default NULL, uppersigma3 double default NULL, lowersigma3 double default NULL, sma20 double default NULL, sma40 double default NULL, sma80 double default NULL, sma100 double default NULL, sma200 double default NULL, insert_time timestamp not null primary key);
create table GBP_USD_1h_TABLE(start_price double, end_price double, max_price double, min_price double, uppersigma1 double default NULL, lowersigma1 double default NULL, uppersigma2 double default NULL, lowersigma2 double default NULL, uppersigma3 double default NULL, lowersigma3 double default NULL, sma20 double default NULL, sma40 double default NULL, sma80 double default NULL, sma100 double default NULL, sma200 double default NULL, insert_time timestamp not null primary key);
create table GBP_USD_day_TABLE(start_price double, end_price double, max_price double, min_price double, uppersigma1 double default NULL, lowersigma1 double default NULL, uppersigma2 double default NULL, lowersigma2 double default NULL, uppersigma3 double default NULL, lowersigma3 double default NULL, sma20 double default NULL, sma40 double default NULL, sma80 double default NULL, sma100 double default NULL, sma200 double default NULL, insert_time timestamp not null primary key);

